-- auto Generated on 2018-06-05 10:28:08 
-- DROP TABLE IF EXISTS Authority;
CREATE TABLE Authority(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	name VARCHAR (50) NOT NULL DEFAULT '' COMMENT '权限名称',
	value VARCHAR (50) NOT NULL DEFAULT '' COMMENT '权限值',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '权限表';
