-- auto Generated on 2018-06-05 10:28:45 
-- DROP TABLE IF EXISTS User;
CREATE TABLE User(
	id BIGINT (15) NOT NULL AUTO_INCREMENT COMMENT 'id',
	username VARCHAR (50) NOT NULL DEFAULT '' COMMENT '账号',
	password VARCHAR (60) NOT NULL DEFAULT '' COMMENT '密码',
	company VARCHAR (50) NOT NULL DEFAULT '' COMMENT '公司',
	department VARCHAR (50) NOT NULL DEFAULT '' COMMENT '部门',
	create_by VARCHAR (50) NOT NULL DEFAULT '' COMMENT '创建人员',
	create_date DATETIME NOT NULL DEFAULT '1000-01-01 00:00:00' COMMENT '创建时间',
	PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '用户表';
